### PR TITLE
feat: enable support for umbrella applications and validate config opts

### PR DESCRIPTION
**Pull request by MikaAK**
Running this in a real umbrella application is a bit rough due to the exporter since you're forced to keep track of metrics and pool them all in the central app that has the exporter. This is a bit flawed because you can no longer allow the application responsible for incrementing the metrics to start the metrics leaving a bigger integration to setup than just using `in_umbrella: true`. 

To change this I've made it so that the supervisor can be started in multiple applications, and the scrape is run from the exporter supervisor across all other supervisor instances in order to build a Prometheus metrics page for all applications, while allowing them to be responsible for their own metrics

This PR changes a few things:

1) The exporter is no longer enabled by default
2) The options are now fully validated and the defaults assigned via validation (done by NimbleOptions)
3) The exporter now scrapes every possible `TelemetryMetricsPrometheus` instance running 
4) Instances are tracked via registered process name instead of via Registry to keep it simple

### CODE REVIEW

**Comment by MikaAK** [comment]
@bryannaegele feel free to contact me if you would like to discuss more `@mika` on the elixir slack or mika@learn-elixir.dev

**Comment by bryannaegele** [comment]
Hey @MikaAK. I can see how this might be confusing given the lack of documentation for umbrella apps.

> Running this in a real umbrella application is a bit rough due to the exporter since you're forced to keep track of metrics and pool them all in the central app that has the exporter.

This is not necessary to do. The app is already designed to have multiple running instances for cases such as this.

https://github.com/beam-telemetry/telemetry_metrics_prometheus/blob/main/test/telemetry_metrics_prometheus_test.exs#L132-L147

In the case of an umbrella application, you would simply need to set a different port and name for each instance. Then you can adjust your prometheus scrape configuration to have multiple targets.

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config

This would look something like this using static configs as an example:

```yaml
 scrape_configs:
    - job_name: "my_umbrella_app"
      static_configs: 
      - targets: ['localhost:5678', 'localhost:5679', 'localhost:5680']
```

If you'd like to open a PR to document this better, it would be welcomed. :)

https://github.com/beam-telemetry/telemetry_metrics_prometheus/issues/38

**Comment by MikaAK** [comment]
@bryannaegele having a separate port for each instance is a bit odd, I'm not sure why you would want to go that route vs having a singular interface, but fair enough, I'll probably create a new package

Having 30 different ports open on every server application seems like a huge waste of resources. It forces an N+1 problem for every application you want to record metrics on that's a library and part of your set of tools. Ontop of that, because of the combinations of different apps the config for Prometheus setup becomes a bit of a hassle to remember and track down all the ports to scrape target for specific apps.

I can see a lot of downsides to this approach and nothing would stop you from doing this approach in this PR, however I would recommend against it for complexity sake 🤷🏽‍♂️

**Comment by bryannaegele** [comment]
That's a very large umbrella project!

There are additional issues that your proposal presents with prometheus in general which doesn't make this a good fit for this library, the most prominent one being that metrics must be grouped together within a single scrape. Since each of your apps can repeat a metric name, concatenating the scrape outputs from a number of different targets could produce an improperly formatted output. There is then an additional burden to the developer to guarantee that every metric is genuinely unique across all of your applications.

https://prometheus.io/docs/instrumenting/exposition_formats/#grouping-and-sorting

It sounds like you have a good idea of what you want but the guardrails that would be required to make this work are outside the scope of this library. If you do decide to pursue this approach further, just be aware of some of these potential issues.

**Pull request closed without merging**
